# Generated by Django 4.0.2 on 2022-02-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_remove_skill_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title',
            new_name='carrera',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='lugarcarrera',
        ),
    ]
