# Generated by Django 4.0.2 on 2022-02-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_skill_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='imagenlugar',
            field=models.ImageField(default=100, upload_to='portafolio/images'),
            preserve_default=False,
        ),
    ]
