# Generated by Django 4.0.2 on 2022-03-03 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0009_alter_skill_imagenlugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=100, null=True, verbose_name='Empresa')),
                ('Cargo', models.CharField(max_length=100, null=True, verbose_name='Cargo')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='description')),
                ('url', models.URLField(blank=True)),
                ('Web', models.URLField(blank=True)),
                ('date', models.DateTimeField(verbose_name=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='imagenlugar',
            field=models.ImageField(upload_to=''),
        ),
    ]
